name: CI

on:
  pull_request:
    branches:
      - main  # Run CI on PRs targeting the main branch

jobs:
  build-and-test:
    name: Build & Test SPM Packages
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2

      - name: Build and test `backend` package
        run: |
          cd backend
          swift build

      - name: Build and test `ios` package
        run: |
          cd ios
          swift build
          swift test

      - name: Build and test `shared` package
        run: |
          cd shared
          swift build